### ISSUE TITLE
Cient is not starting on Archlinux

### ISSUE THREAD

**Issue by mac-linux-free** [joshpatten/PVE-VDIClient#1]
raceback (most recent call last):
  File "/home/mac/PVE-VDIClient/vdiclient.py", line 3, in <module>
    import PySimpleGUIQt as sg # pip install PySimpleGUIQt
  File "/home/mac/.local/lib/python3.10/site-packages/PySimpleGUIQt/__init__.py", line 2, in <module>
    from .PySimpleGUIQt import *
  File "/home/mac/.local/lib/python3.10/site-packages/PySimpleGUIQt/PySimpleGUIQt.py", line 25, in <module>
    from PySide2.QtWidgets import QApplication, QLabel, QWidget, QLineEdit, QComboBox, QFormLayout, QVBoxLayout, QHBoxLayout, QListWidget, QDial, QTableWidget
ImportError: libshiboken2.abi3.so.5.15: cannot open shared object file: No such file or directory

Thank you :)

**Comment by joshpatten** [comment]
https://github.com/pyinstaller/pyinstaller/issues/4044

What version of Python are you using, and can you show me the output of
`pip list`?

Also, as I don't have a mac to test on, can you run the following python
script and reply with the output?

import os
print(os.name)

**Comment by joshpatten** [comment]
Well I feel super dumb for not reading your whole comment, sorry about that!

You can ignore everything I said, except I do need the output of the command `pip3 list`

**Comment by mac-linux-free** [comment]
> Well I feel super dumb for not reading your whole comment, sorry about that!
> 
> You can ignore everything I said, except I do need the output of the command `pip3 list`

Package                       Version
----------------------------- -------------------------------------------------------------------------------
absl-py                       1.0.0
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
ansiwrap                      0.8.4
anytree                       2.8.0
apparmor                      3.0.4
appdirs                       1.4.4
APScheduler                   3.8.1
apsw                          3.36.0.post1
arandr                        0.1.10
asciinema                     2.1.0
asteval                       0.9.26
async-timeout                 4.0.2
attrs                         21.4.0
AUR                           2021.11.20.2.41.2
Automat                       20.2.0
Babel                         2.9.1
Bauerbill                     2021.12.31.5.21.59
bauh                          0.9.28
bcrypt                        3.2.0
Beaker                        1.11.0
beautifulsoup4                4.10.0
borgbackup                    1.2.0
brotlicffi                    1.0.9.2
btrfsutil                     5.16.2
CacheControl                  0.12.6
cchardet                      2.1.7
ceph                          1.0.0
ceph-volume                   1.0.0
cephfs                        2.0.0
cephfs-shell                  0.0.1
cffi                          1.15.0
chardet                       4.0.0
charset-normalizer            2.0.10
click                         8.0.4
cmapy                         0.6.6
colorama                      0.4.4
coloredlogs                   15.0.1
colorsysplus                  2021.11.20.2.41.2
ConfigArgParse                1.5
constantly                    15.1.0
contextlib2                   0.6.0.post1
crit                          0.0.1
cryptography                  36.0.1
css-parser                    1.0.6
cssselect                     1.1.0
cupshelpers                   1.0
cycler                        0.10.0
dbus-next                     0.2.3
defusedxml                    0.7.1
distlib                       0.3.4
distro                        1.7.0
dnspython                     2.2.0
docopt                        0.6.2
docutils                      0.16
entrypoints                   0.4
evdev                         1.4.0
fabulous                      0.4.0
feedparser                    6.0.2
file-magic                    0.4.0
fonttools                     4.29.1
frozenlist                    1.3.0
future                        0.18.2
getkey                        0.6.5
Glances                       3.2.4
gpg                           1.17.1
greenlet                      1.1.2
grpcio                        1.43.2
html2text                     2020.1.16
html5-parser                  0.4.10
html5lib                      1.1
humanfriendly                 10.0
hyperlink                     21.0.0
idna                          3.3
ifaddr                        0.1.7
imagesize                     1.3.0
IMDbPY                        2021.4.18
img2pdf                       0.4.3
importlib-metadata            4.8.1
importlib-resources           5.4.0
incremental                   21.3.0
inputs                        0.5
iotop                         0.6
isounidecode                  0.3
jeepney                       0.7.1
Jinja2                        3.0.3
joblib                        1.1.0
jrnl                          2.8.3
keyring                       23.4.0
keyutils                      0.6
kiwisolver                    1.3.2
lensfun                       0.3.3
LibAppArmor                   3.0.4
libtorrent                    2.0.5-build-libtorrent-rasterbar-src-libtorrent-rasterbar-2.0.5-bindings-python
libvirt-python                8.1.0
lit                           13.0.1.dev0
llfuse                        1.4.1
louis                         3.20.0
lxml                          4.7.1
Mako                          1.1.6
Markdown                      3.3.6
MarkupSafe                    2.0.1
matplotlib                    3.5.1
mechanize                     0.4.6
mediapipe                     0.8.9.1
MemoizeDB                     2021.11.20.2.41.2
meson                         0.61.2
more-itertools                8.10.0
msgpack                       1.0.3
multidict                     6.0.2
multivolumefile               0.2.3
musicbrainzngs                0.7.1
mutagen                       1.45.1
nagstamon                     3.8.0.arch
natsort                       8.1.0
netifaces                     0.11.0
netsnmp-python                1.0a1
nftables                      0.1
nose                          1.3.7
notify2                       0.3.1
numpy                         1.22.3
ocrmypdf                      13.4.0
openpaperwork-core            2.1.0
openpaperwork-gtk             2.1.0
openshot-qt                   2.6.1
opensnitch-ui                 1.5.0
ordered-set                   4.0.2
packaging                     20.9
paperwork                     2.1.0
paperwork-backend             2.1.0
paperwork-shell               2.1.0
parameterized                 0.8.1
paramiko                      2.9.2
parsedatetime                 2.6
patool                        1.12
pbget                         2021.12.24.10.23.57
pdfarranger                   1.8.2
pdfminer.six                  20201018
peewee                        3.14.8
pep517                        0.12.0
pikepdf                       5.0.1
Pillow                        9.0.1
pip                           21.0
pluggy                        0.13.1
ply                           3.11
pm2ml                         2021.11.20.2.41.2
Powerpill                     2021.11.20.2.41.2
progress                      1.6
protobuf                      3.19.4
proxmoxer                     1.2.0
psutil                        5.9.0
PTable                        0.9.2
pulsectl                      22.1.3
pulsemixer                    1.5.1
pwquality                     1.4.4
py7zr                         0.17.4
pyalpm                        0.10.6
pyaml                         21.10.1
PyAudio                       0.2.11
pybind11                      2.9.1
pycairo                       1.20.1
pychm                         0.8.6
pycountry                     22.1.10
pycparser                     2.21
pycryptodomex                 3.12.0
pycups                        2.0.1
pycurl                        7.44.1
pydbus                        0.6.0
pyenchant                     3.2.2
pyfakewebcam                  0.1.0
Pygments                      2.11.2
PyGObject                     3.42.0
pyinotify                     0.9.6
pykerberos                    1.2.1
pylast                        4.4.0
PyLyrics                      1.1.0
PyNaCl                        1.4.0
pyocr                         0.9.dev0+gf9f93bb.d20211202
PyOpenGL                      3.1.5
pyOpenSSL                     21.0.0
pyparsing                     3.0.1
pyparted                      3.11.7
pypillowfight                 0.3.0
pyppmd                        0.17.3
Pypubsub                      4.0.3
PyQt5                         5.15.6
PyQt5-sip                     12.9.1
PyQtWebEngine                 5.15.5
PySDL2                        0.9.11
PySide2                       5.15.2.1
PySide6                       6.2.3
PySimpleGUIQt                 0.35.0
PySocks                       1.7.1
python-dateutil               2.8.2
python-Levenshtein            0.12.2
python-poppler-qt5            21.1.0
python-slugify                5.0.2
python-xapp                   2.2.1
python-xlib                   0.31
pytz                          2021.3
pytz-deprecation-shim         0.1.0.post0
pyudev                        0.22.0.dev20211202
pywal                         3.3.0
pyxdg                         0.27
PyYAML                        6.0
pyzmq                         22.3.0
pyzstd                        0.15.2
qreator                       20.2.1
qrencode                      1.2
qrtools                       2.1
radiotray                     0.7.3
rados                         2.0.0
ranger-fm                     1.9.3
rbd                           2.0.0
rednotebook                   2.22
Reflector                     2021.11.20.2.41.3
regex                         2021.11.10
reportlab                     3.6.6
requests                      2.27.1
requests-kerberos             0.14.0
requests-unixsocket           0.3.0
resolvelib                    0.5.5
retrying                      1.3.3
rgw                           2.0.0
rpm                           4.17.0
Rx                            3.2.0
ryzen-ppd                     0.3
scikit-learn                  1.0.2
scipy                         1.8.0
SCons                         4.3.0
screenkey                     1.5
SecretStorage                 3.3.1
Send2Trash                    1.8.0
setproctitle                  1.2.2
setuptools                    59.3.0
setuptools-scm                6.4.2
setuptools-scm-git-archive    1.1
sgmllib3k                     1.0.0
shiboken2                     5.15.2.1
shiboken6                     6.2.3
simplebayes                   1.5.8
sip                           6.5.1
six                           1.16.0
smbus                         1.1
snowballstemmer               2.2.0
solaar                        1.1.1
soundconverter                4.0.3
soupsieve                     2.3.1
Sphinx                        4.4.0
sphinx-rtd-theme              1.0.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
SQLAlchemy                    1.4.30
TBB                           0.2
team                          1.0
text-unidecode                1.3
texttable                     1.6.4
threadpoolctl                 2.2.0
toml                          0.10.2
tomli                         2.0.0
torbrowser-launcher           0.3.5
tqdm                          4.63.0
Twisted                       21.7.0
typing-extensions             4.1.0
tzdata                        2021.5
tzlocal                       2.1
udiskie                       2.4.2
Unidecode                     1.3.2
unrardll                      0.1.5
urllib3                       1.26.8
vdf                           3.4
vobject                       0.9.6.1
vorta                         0.8.3
webencodings                  0.5.1
websocket-client              1.2.3
websockets                    10.2
wheel                         0.37.1
Whoosh                        2.7.4
wxPython                      4.0.7.post2
xattr                         0.9.9
XCGF                          2021.11.20.2.41.3
XCPF                          2021.12.24.10.22.41
yarl                          1.7.2
youtube-dl                    2021.12.17
yt-dlg                        1.8.4
ytmusicapi                    0.21.0
zeroconf                      0.38.4
zim                           0.74.3
zipp                          3.7.0
zope.interface                5.4.0

**Comment by mac-linux-free** [comment]
ok this helps...thank you
