### ISSUE TITLE
PySimpleGUI New Licensing Requirements

### ISSUE THREAD

**Issue by GoremanX** [joshpatten/PVE-VDIClient#101]
PySimpleGUI library now needs a very onerous LICENSE to use, which requires copying and pasting a super-long license key into the GUI, which it asks for every time the GUI is launched. There needs to be a different GUI library for this VDI Client, otherwise we absolutely cannot use it like this.

**Comment by joshpatten** [comment]
If you look at the requirements batch/shell files I have restricted PySimpleGUI to any version less than 5.0.0, which is where this draconian license was instated. If you're experiencing this on the 4.x version of PySimpleGUI then let me know what version of PySimpleGUI you're running and I'll make sure to install a version earlier than that.

Regarding implementing a different UI library, I am not a software developer, just someone who had a need and shared what I built with the world. I would need someone else to contribute a UI library replacement.

**Comment by GoremanX** [comment]
You're correct, I missed that part. I was following a guide that installs VDI Client on a different distribution and it doesn't take into account the different possible versions of PySimpleGUI or some of the more recent changes to VDI Client. I just tried with <5.0.0 as a version string and now it works. Thank you.

That license thing... wow 🙄 it's deplorable. I wonder if it's worth forking the most recent <5 version

**Comment by blindrain** [comment]
on windows  the requirements script still installs the current version,  even with it set <5.0.0  but if i copy and pastes the command from the bat file to command prompt   it works great.
