### ISSUE TITLE
Unable to connect to graphic server

### ISSUE THREAD

**Issue by dwpurser** [joshpatten/PVE-VDIClient#11]
![UnableToConnectToGraphicServer](https://user-images.githubusercontent.com/8032383/163682260-b38f3765-f97e-457e-acaf-e1e33c63516a.png)
Is this a configuration error with my proxmox installation or PVE-VDIClient?

When I click connect button next to the server in the list, I recieve the error "Unable to connect to graphic server - could not connect to proxy server 127.0.0.1: Connection refused"

This is my config file:
[General]
title = Proxmox VDI
icon=vdiicon.ico
logo=vdilogo.png
kiosk=false
theme=Dark

[Authentication]
auth_backend=pve
auth_totp=false
tls_verify=false

[Hosts]
192.168.198.8=8006

**Comment by joshpatten** [comment]
Can you please post a copy of the VV file you download from proxmox?

**Comment by dwpurser** [comment]
Thank you for helping, see attached
[pve-spice.vv.txt](https://github.com/joshpatten/PVE-VDIClient/files/8500639/pve-spice.vv.txt)
.

**Comment by dwpurser** [comment]
reviewing the file it referred to the server with FQDN and I saw it was not added to my pi-hole so it could be resolved. Added FQDN and IP address of my proxmox server and it worked like expected!
