### ISSUE TITLE
Way to limit the video quality or network bandwidth consumption

### ISSUE THREAD

**Issue by vi4869** [joshpatten/PVE-VDIClient#114]
I realized the client is consuming a lot of bandwidth (around 200 - 250 Mbps). I was searching around but didn't any related topics. Wonder if there a way to limit the consumption or reduced the video quality? Thanks!

**Comment by joshpatten** [comment]
This is not a VDI client issue, rather it is an issue that should be filed against the SPICE client (virt-viewer).
