### ISSUE TITLE
#FEATURE-REQUEST: Coloring the VM Status

### ISSUE THREAD

**Issue by FleX246** [joshpatten/PVE-VDIClient#119]
Hey guys,

I would like to make a feature request here.
What I would like is to be able to color the status of the individual VMs.

Is this a lot of work?

Perhaps, since not everyone will want to use this, via an entry in the config file so that you can deactivate or activate it.

I have unpacked my "its over 9000" mspaint skills and created a rough idea of ​​how I would imagine it.

Thank you very much :-)

![Unbenannt](https://github.com/user-attachments/assets/1dce462a-02ea-4cb6-b3b5-5919981e6444)

**Comment by wd-h** [comment]
Hi, the feature is done below.
https://github.com/wd-h/PVE-VDIClient

![錄製內容 2024-09-04 205149](https://github.com/user-attachments/assets/cd6a2964-d72b-4b92-b47b-1c32a5b3cebe)

**Comment by FleX246** [comment]
Thank you !
Worked perfectly
