### ISSUE TITLE
Portable application possible ?

### ISSUE THREAD

**Issue by docop** [joshpatten/PVE-VDIClient#13]
Hi
 I would like to say it's very nice to have a fully working standalone app. quite great. For the linux part, is an Appimage could be possible in order to have it fully portable ?  and avoid python stuff requirement to be install prior..

Thanks

**Comment by joshpatten** [comment]
I believe pyinstaller can create a single file binary, I will load this up and try it out, then create a script when I get it building properly.

**Comment by joshpatten** [comment]
I've updated the readme with instructions on how to build a binary in Linux. Unfortunately these binaries don't seem to be portable across different distros of Linux (example, a build on Alpine Linux will not execute on Ubuntu Linux).

**Comment by docop** [comment]
Of course an appimage do have the advantage to having all dep togerther and mostly not that much issues over different bin..
 i did built and install : pip install proxmoxer
python3 -m venv my_env   ..
 at end the vdiclient don't want to start and still complain about proxmoxer  .. unhandle exception..

**Comment by joshpatten** [comment]
It would help to see what the full stack trace is...
