### ISSUE TITLE
Can't connect to virt-viewer Windows 11

### ISSUE THREAD

**Issue by ankoo1998** [joshpatten/PVE-VDIClient#14]
VDIClient cant connect to virt-viewer, get error message "Cant connect to graphics driver"

**Comment by joshpatten** [comment]
You're really not giving a lot to go on here, please be more
descriptive/specific

**Comment by hidrawlic** [comment]
I encountered this as well.  

Step(s) to reproduce:  After successful login to client, click on VM from list
Expected result:  Spice client displays VM desktop
Actual result:  Error message pops up with "Unable to connect to the graphic server -" (that's verbatim, hyphen also)
- User has privs VM.PowerMgmt, VM.Console and VM.Audit; root user results in the same error
- VM has Spice enabled in settings
- Tested both Windows and Linux VMs so pretty confident that it's not OS-specific
- Thin client OS in my case is Alpine (64-bit) with Openbox.  Network is wired, no strange VLANs/bridging/routing

Nothing prints to stderr so apparently this is working as designed but I can't find that verbiage anywhere in VDIClient.py so I have no clue what would cause it.

**Comment by Kuruton8** [comment]
Same here.
I tried on completely clean windows10 but still stucks.
I can connect to VMs by using Remote viewer opening from "pve-spice.vv" which I downloaded from web interface.

**Comment by incoggnito** [comment]
Same Same, can't connect on win10.
PVE version is 7.1-12

**Comment by joshpatten** [comment]
I need some information on what might be going wrong:

Please attach a copy of the .vv file
Please set inidebug=True in your INI file, and copy the contents of the
window that pops up into a text file and attach it here.

**Comment by incoggnito** [comment]
Yeah, already debug your src. The difference between the generated inistring and my downloaded vv-file is in the proxy line.
http://VDIDebian.mywebsite.net:3128 <-> http://192.168.1.1:3128
Maybe i don't understand the [SpiceProxyRedirect] config line correctly.
Is there any further documentation?

**Comment by Kuruton8** [comment]
This issue was caused by host name.
Seeing the "INI debug" joshpatten said, you can find "proxy = _{your proxmox's host name}_:3128".
In such this situation, you can't resolve your host name unless you added "_your proxmox's host name_" record on your private (or public) DNS server.

So, you need to add a line on your vdiclient.ini like below ;

[SpiceProxyRedirect]
_{your proxmox's host name}_:3128 = _{your proxmox's ip adress}_:3128

_{your proxmox's host name}_ can be seen from web interface, [_Node_]→[System]→[Hosts] (next to the ip adress).
Sorry for bad English but, I hope this will help you.

**Comment by joshpatten** [comment]
Ok lets try this:

Paste the contents of the vv file that you download from proxmox

Set the inidebug parameter in the config file to True

Paste the contents of the ini debug window when it pops up

My hunch is there might be something wrong with the proxy redirect logic
thats falsely changing the proxy host.
