### ISSUE TITLE
No module names 'requests'

### ISSUE THREAD

**Issue by MarioMartins-MM** [joshpatten/PVE-VDIClient#19]
Saw a few issues regarding to ARM based clients. And here is my case.

I firstly got the error "No module named PySimpleGUI." Then I manually and additionally installed  the module using pip3. 
Then, I got the error  "No module named tkinter". So, I installed a few other packages as mentioned in another issue thread here.
But now I'm getting the error below:

### sms@debian-pi4:~/PVE-VDIClient$ ./vdiclient.py
Traceback (most recent call last):
  File "/home/sms/PVE-VDIClient/./vdiclient.py", line 9, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'requests'
sms@debian-pi4:~/PVE-VDIClient$

Trying to run it on Debian 11 (Bullseye) on a Raspi-4 with no Desktop environment.
Any thoughts?
Thanks

**Comment by joshpatten** [comment]
Try running the following commands, then run the VDI client again:

pip3 uninstall PySimpleGUIQt
apt install python3-tk

**Comment by MarioMartins-MM** [comment]
I already did. And that’s when I got the error mentioned above.
Any other thoughts?

**Comment by joshpatten** [comment]
so you made sure to `apt install python3-tk` ? Because your python install
doesn't appear to have tkinter available

You might try `apt --reinstall install python3-tk` to ensure the package
files get installed.

**Comment by MarioMartins-MM** [comment]
There we go...

### sms@debian-pi4:~$ sudo pip3 uninstall PySimpleGUIQt
[sudo] password for sms:
WARNING: Skipping PySimpleGUIQt as it is not installed.
### sms@debian-pi4:~$ sudo apt install python3-tk
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-tk is already the newest version (3.9.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
### sms@debian-pi4:~$ ./PVE-VDIClient/vdiclient.py
Traceback (most recent call last):
  File "/home/sms/./PVE-VDIClient/vdiclient.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
sms@debian-pi4:~$

**Comment by joshpatten** [comment]
ok now you're getting a different error, you can resolve it by running `apt
install python3-requests`

I'll add that to requirements.sh

**Comment by MarioMartins-MM** [comment]
Easy !... It works now. Thanks for your help.
