### ISSUE TITLE
Token Authentication Failing

### ISSUE THREAD

**Issue by blindrain** [joshpatten/PVE-VDIClient#21]
When Setting Token up in config it still prompts for username and password.  

Below is my config where you can see I've tried several different Scenarios.  the only 2 parameters that seem to work are user and token name  I WhenI get an error I can see the name there. but usually I don't get an error  I only get the login screen 

`[General]
# This is the title that is diplayed to the user
title = PercFab VDI 
# This is the PySimpleGui Theme that is used. Run pvevdi.py with flag `--list_themes` for a list of themes
theme = LightRed
# Program Icon
icon = vdiicon.ico
# Logo displayed on all windows
logo = vdiclient.png
# Enable Kiosk mode, which does not allow the user to close anything
kiosk = False
# Enable/Disable Fullscreen mode (not applicable in Kiosk mode)
fullscreen = False
# Enable displaying SPICE ini file before opening virt-viewer
inidebug = False

[Authentication]
# This is the authentication backend that will be used to authenticate
auth_backend = pve
# If enabled, 2FA TOTP entry dialog will show
auth_totp = false
# If disabled, TLS certificate will not be checked
tls_verify = True
# User name
user = vdiclient
# API Token Name
#token_name = vdiclient@pve!test
#API Token Value
#token_value = a6fd7ccc-5d1e-4ece-b653-019db3c23f63
#token_name = Chicken
#token_value = 01dcb2f8-8fb7-489a-8353-75fccdd147ed
#01dcb2f8-8fb7-489a-8353-75fccdd147ed  # vdiclient@pve!Chicken
`

**Comment by blindrain** [comment]
Further Testing with 2 different tokens and Privilege Separation turned on  I still have to log in but I do see a difference in VMS listed based on the token.  but is there a way to bypass the user name and password and Just Give the user the option of VMs to choose from? This video Stated that to token option supported auto login.

**Comment by joshpatten** [comment]
You're totally right, I missed the passwordless login, I released version 1.0.8 to resolve this issue: https://github.com/joshpatten/PVE-VDIClient/commit/f9be014ea201eb9e4edb9092855aee89e31e14b0

**Comment by blindrain** [comment]
Tested This works now.   All you need is username token and token name  no password in the config file
