### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by damo2929** [joshpatten/PVE-VDIClient#26]
would it be possible to add buttons for the below actions if permission allow
Power on 
Reset
Stop
Shutdown 

Snapshots.
take snapshot
delete snapshot
roll back.

**Comment by yangsm88888** [comment]
The above functions are better, and are there plans to support the rdp protocol?

**Comment by joshpatten** [comment]
As this is intended to be a simple to use VDI client for end users and not
a management client, these functions aren't part of the scope of this
project.

Regarding RDP, there isn't really a good way to implement RDP
cross-platform, and the inconsistency between different environments means
that whatever got developed to work in one environment wouldn't necessarily
work correctly in another.
