### ISSUE TITLE
[Feature Request] Select and Remember USB Devices for Redirection to VM

### ISSUE THREAD

**Issue by crzp** [joshpatten/PVE-VDIClient#28]
First of all:
**great project, i'm loving it so far.** 

While I was discussing the use of your client for a new VDI project with my colleague we came across the USB pass through feature, which is essential for us. It needs to work properly and reliably. 
Our Clients mainly will use Windows PCs to connect to the VDI. 

**I guess my question is** if it's possible to build a select and remember function for the USB devices which need to be redirected to the VM and then pass that information to the virt-viewer at start? 
For the user to select all needed USB devices in the virt-viewer after every connection is not a desired behavior. 

_Just my 2 cents:_
The need in the market for a better and more open approach to VDI is huge. Especially after the prognosis for the dying Terminal Server from Microsoft and the acquisition of VMWare from Broadcom.  
So to build a reliable VDI with Proxmox and other open-source tools would be huge, and for me personally, a huge win for the open-source community.

**Comment by joshpatten** [comment]
So the best I could come up with is to be able to define custom parameters in the ini file that are passed through to remote-viewer.

I have updated the example ini file with these changes and released a new MSI build, please let me know if this works for you.

**Comment by joshpatten** [comment]
I'll need to study the .vv file options for setting USB passthrough, if
they exist, so if you have any insight into this please respond with that
information.

**Comment by joshpatten** [comment]
After a bit of research I think you're going to need to use a usb filter to do this

see: https://www.mankier.com/1/remote-viewer and search for usb-filter

You can add this option in the AdditionalParameters section of the ini file
