### ISSUE TITLE
Feature Request - Multi Server Drop Down

### ISSUE THREAD

**Issue by blindrain** [joshpatten/PVE-VDIClient#32]
Would be nice to have a multi server drop down. 

I would say  do something like 
```
[Hosts]
# Hosts are entered as `IP/FQDN = Port`
pve2.percfab.com = 443 = Production
help.itmethod.net = 443 = Production
pve34.percfab.com = 443 = Dev
pve.itmethod.net = 443 = Dev
```
Where the Third parameter is the group / Nice Name for the Groups continue to try them in order.   but if none of the hosts have a Third paramer to ignore the groups.   

or maybe  handle the config file like this would be easier
```
[Hosts]
# Hosts are entered as `IP/FQDN = Port`
Name = Production
pve2.percfab.com = 443
help.itmethod.net = 443

[Hosts.1]
# Hosts are entered as `IP/FQDN = Port`
Name = Dev
pve34.percfab.com = 443
pve.itmethod.net = 443
```

**Comment by joshpatten** [comment]
I'll put this on the roadmap, thanks!

**Comment by blindrain** [comment]
CAn you post the Roadmap so we can see planned updates/ Features?

**Comment by joshpatten** [comment]
I've added a roadmap label to each issue that's going on the roadmap (this one included)

**Comment by joshpatten** [comment]
In looking at this, the most efficient way to accomplish this is to combine the Hosts and Authentication sections, and have the INI file broken down into Hosts.Name sections, and have the dropdown list derive the list of names from the .Name portion of the INI file.

This would unfortunately break backward compatibility, but would make things much more manageable, vs having separate Hosts and Authentication sections for each host grouping.

Thoughts?

**Comment by blindrain** [comment]
Sounds like a good way forward.  And to bring backwards compatibility into the mix have the code test for the names sections and if it don't exist revert to read config normally.

**Comment by joshpatten** [comment]
The latest release implements mutli-cluster support, check out the example INI file and give it a go, let me know if you have any issues!

**Comment by blindrain** [comment]
Well the backwards compatibility works. 

Have not tested new config file yet

**Comment by blindrain** [comment]
I accidentally left the authentication section and it threw an error saying the host section doesnt exist. Whic I assume is to expected.   It seems to be working good.

**Comment by blindrain** [comment]
This is working Great
