### ISSUE TITLE
Video about this wonderful tool [ this is not an issue ]

### ISSUE THREAD

**Issue by gilbertoferreira** [joshpatten/PVE-VDIClient#34]
I manage a Youtube channel about Proxmox VE.
I stumbed across this project about VDI SPICE over PVE.
So I made video about it (Brazilian Portuguese only! Sorry! But you can enable subs!)
I hope you enjoy it.

Thanks

https://www.youtube.com/watch?v=kxm-JtnLWmc

**Comment by joshpatten** [comment]
Very cool, thanks!
