### ISSUE TITLE
Keyboard is not auto captured

### ISSUE THREAD

**Issue by M6268** [joshpatten/PVE-VDIClient#35]
I am using t2 linux on macbook air.
yesterday i have upgraded from ubuntu 22.04 to 22.10.
after upgrade remote-viewer working good but it does not capture keyboard by default i have to use usb pass through to get keyboard full working otherwise host os will take keyboard input, if usb pass though enabled then host wont able to use them until PT is disabled.
if i press window/super button host os will shows corresponding action not the PVE vm.

**neofetch info**

OS: Ubuntu 22.10 x86_64 
Host: MacBookAir9,1 1.0 
Kernel: 6.0.2-t2 
Uptime: 1 hour, 9 mins 
Packages: 2181 (dpkg), 27 (flatpak), 8 (snap) 
Shell: bash 5.2.2 
Resolution: 2560x1600 
DE: GNOME 43.0 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru-red [GTK2/3] 
Icons: Yaru-red [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-1030NG7 (8) @ 3.500GHz 
GPU: Intel Iris Plus Graphics G7 
Memory: 2996MiB / 7753MiB

**Comment by joshpatten** [comment]
This is unrelated to the VDI client as your issue appears to be related to remote-viewer
