### ISSUE TITLE
Incapaz de conectar ao servidor de grafico

### ISSUE THREAD

**Issue by rozenraurio** [joshpatten/PVE-VDIClient#38]
fiz a configuração conforme documento porem não consigo acessa
![pvevdi00](https://user-images.githubusercontent.com/5703382/202045096-895b755b-1b4a-4fd5-b0a8-f3c57e985894.PNG)
![pvevdi01](https://user-images.githubusercontent.com/5703382/202045106-dc5f39a6-f065-4e27-953c-7121818f9d79.PNG)
![pvevdi02](https://user-images.githubusercontent.com/5703382/202045113-d5e43594-af4d-4aad-9816-01ac494c68ed.PNG)
caso alguém posso me ajudar agradeço

**Comment by charlespjo** [comment]
vc conceguiu reolver?

**Comment by EdsonMelo** [comment]
Alguem conseguiu resolver esse problema? desde ja agradeço
