### ISSUE TITLE
List Formatting

### ISSUE THREAD

**Issue by completion** [joshpatten/PVE-VDIClient#4]
Currently, all the VMs and containers are put in one big list. I currently have ~30 total so the UI window extends past my screen. So it would be beneficial to add some formatting. Something along the lines of making the list scroll able or add multiple columns. Also differentiating between VMs and containers  would be helpful.

**Comment by joshpatten** [comment]
completion,

As this tool is intended for end-user VDI access differentiating between containers and vm's isn't really in the scope, however I did implement scrolling when going past 5 VMs in [this commit](https://github.com/joshpatten/PVE-VDIClient/commit/6065985159fdb36ef1bbe4d843425d0c1bac6dc6)
