### ISSUE TITLE
PySimpleGui Themes in Vdiclient.ini.example

### ISSUE THREAD

**Issue by chrishac-git** [joshpatten/PVE-VDIClient#40]
On line 4 of the vdiclient.ini.example file, it reads as:
# This is the PySimpleGui Theme that is used. Run pvevdi.py with flag `--list_themes` for a list of themes
this should be:
# This is the PySimpleGui Theme that is used. Run vdiclient.py with flag `--list_themes` for a list of themes

i've attached a screenshot if needed
![Screenshot from 2022-12-13 20-36-19](https://user-images.githubusercontent.com/64866842/207440674-8c56aa6b-d51f-4108-a2c4-64cafbb4c08e.png)

Great Project saves me having to log in to proxmox UI every time I need access.

**Comment by joshpatten** [comment]
Fixed in commit c2221da
