### ISSUE TITLE
Install guide is not idiot proof...

### ISSUE THREAD

**Issue by lordratner** [joshpatten/PVE-VDIClient#41]
Hi there. Loving the VDI so far. Definitely making my life easier. 

For the install process in the readme, Windows was pretty straight forward, but the Linux version could leave a beginner lost. 

The part where you clone the repository isn't in there. I know it seems obvious, but just a month ago that would have completely confounded me. Might be nice to have a more granular step-by-step. Anyways, Thanks!

**Comment by lordratner** [comment]
My suggested change:

apt install python3-pip virt-viewer git
git clone https://github.com/joshpatten/PVE-VDIClient.git
cd ./PVE-VDIClient/
chmod +x requirements.sh
./requirements.sh
cp vdiclient.py /usr/local/bin
chmod +x /usr/local/bin/vdiclient.py

**Comment by lordratner** [comment]
It may also be useful to add the most recent version of Qt, either in the first command or to the requirements.sh script. Probably the latter. I couldn't get past #23 until I got Qt to update.

**Comment by joshpatten** [comment]
Fixed in commit de40887
