### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found

### ISSUE THREAD

**Issue by lordratner** [joshpatten/PVE-VDIClient#42]
Hi, I'm having the same problem from issue #23 

I've tried uninstalling PySimpleGUIQt, but doing so then gives the Traceback  error:

No Module name 'tkinter'

But pip install tk shows the package already installed. Reinstalling PySimpleGUIQt brings back the original error. 

I'm running the program with: python3 /usr/local/bin/vdiclient.py

Thanks

**Comment by lordratner** [comment]
Looks like the issue was the version of Qt installed? I ran "apt install qt5-doc" and it added 61 packages:

geoclue-2.0 iio-sensor-proxy libdouble-conversion3 libmd4c0 libpcre2-16-0 libqt5core5a libqt5dbus5 libqt5gui5 libqt5help5 libqt5network5
  libqt5positioning5 libqt5printsupport5 libqt5qml5 libqt5qmlmodels5 libqt5quick5 libqt5sensors5 libqt5sql5 libqt5sql5-sqlite libqt5svg5 libqt5webchannel5
  libqt5webkit5 libqt5widgets5 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinput0 libxcb-xkb1 libxkbcommon-x11-0 qt3d5-doc
  qt5-assistant qt5-doc qt5-gtk-platformtheme qtbase5-doc qtcharts5-doc qtchooser qtconnectivity5-doc qtdatavisualization5-doc qtdeclarative5-doc
  qtgraphicaleffects5-doc qtlocation5-doc qtmultimedia5-doc qtnetworkauth5-doc qtquickcontrols2-5-doc qtquickcontrols5-doc qtscript5-doc qtscxml5-doc
  qtsensors5-doc qtserialbus5-doc qtserialport5-doc qtsvg5-doc qttools5-doc qttranslations5-l10n qtvirtualkeyboard5-doc qtwayland5-doc qtwebchannel5-doc
  qtwebengine5-doc qtwebsockets5-doc qtwebview5-doc qtx11extras5-doc qtxmlpatterns5-doc

Then it worked.

**Comment by joshpatten** [comment]
I decided to deprecate using Qt as it was proving problematic for a lot of people. Please pull the latest version in and run `pip3 install PySimpleGUI` to install the base PySimpleGUI library.
