### ISSUE TITLE
"Unable to read supplied configuration from any location"

### ISSUE THREAD

**Issue by ChrisCross1337** [joshpatten/PVE-VDIClient#43]
Using the .msi in the release, I went ahead and installed vdi. I then went ahead and used the .ini.example in your repo, configed it to that of my pve instance and used the config locations  for windows installs. Can you assist on this issue? I'm currently on windows 11. Thanks in advance my friend!

**Comment by joshpatten** [comment]
You need to enable inidebug option, then you need to see what the 'proxy' value is set to. Once you've got that information, you need to add a redirect in the SpiceProxyRedirect section of the config file to point to the correct IP/FQDN of your server. See the example config file for more information.
