### ISSUE TITLE
How does multiple hosts work?

### ISSUE THREAD

**Issue by doughnet** [joshpatten/PVE-VDIClient#44]
I add multiple hosts in the configuration file but it only prompts the first host listed and doesn't inquire with the others.

How should this work out?

**Comment by UcANteKMe** [comment]
Host list in the login screen could be nice I think.

**Comment by joshpatten** [comment]
The intention of the host list is for different hosts within the cluster, if the first host can't be contacted it will try the second and so on. This is intended to be an end-user VDI solution that comes pre-deployed from an IT admin, so simplicity of use is key.

**Comment by doughnet** [comment]
> The intention of the host list is for different hosts within the cluster, if the first host can't be contacted it will try the second and so on. This is intended to be an end-user VDI solution that comes pre-deployed from an IT admin, so simplicity of use is key. 

Makes sense. But what if the a user needs to use VM2 which is HOST2 and HOST1 is active. There is no way to reach HOST2 if HOST1 is active.
