### ISSUE TITLE
Being able to set a background image

### ISSUE THREAD

**Issue by BasToTheMax** [joshpatten/PVE-VDIClient#46]
Title says it all

**Comment by ciroiriarte** [comment]
![ok-okay](https://user-images.githubusercontent.com/1750260/222938720-3e2d889f-b523-4866-b045-763387fc3beb.gif)

**Comment by blindrain** [comment]
Back Ground image where?  the login screen? you can change the PVE VDI image to whatever you want with the config file or just change out the file.

**Comment by joshpatten** [comment]
Closing this as it doesn't make sense, you can change the logo out as needed (see example ini file)
