### ISSUE TITLE
Unable to connect to graphic server - could not connect to proxy server : Connection refused

### ISSUE THREAD

**Issue by chaospup** [joshpatten/PVE-VDIClient#50]
I am getting the following message after I select the server from the list after entering user & password
     "Unable to connect to graphic server - could not connect to proxy server 23.217.138.110: Connection refused"

both the Debian client running PVE-VDIClient and the PVE server are on the same subnet. 
Thank You in advance for any help, I am a noob.

VV file::
[virt-viewer]
title=VM 101 - Windows10
type=spice
password=5436bb5d22a8a58770432350c27db45ce7277d4c
tls-port=61000
host=pvespiceproxy:64067a18:101:jld01::f6d4573455f257f5561d2f8786d2e1a7e7ea530f
secure-attention=Ctrl+Alt+Ins
host-subject=OU=PVE Cluster Node,O=Proxmox Virtual Environment,CN=jld01.net.io
proxy=http://192.168.10.5:3128

vdiclient.ini file::
[General]
title = VDI
icon=/home/jld/PVE-VDIClient/vdiicon.ico
logo=/home/jld/PVE-VDIClient/vdilogo.png
kiosk=false

[Authentication]
auth_backend=pve
auth_totp=false
tls_verify=false

[Hosts]
192.168.10.5 = 8006

**Comment by joshpatten** [comment]
So if you look at the IP address that remote-viewer is attempting to
connect to (23.217.138.110) it appears that the vv file that Proxmox is
providing has a DNS address that's resolving to something different than
what you have configured.

Here's what you can do to troubleshoot this and set the correct ini file
parameters:

   1. Set `inidebug=true` in the `General` section of the ini file
   2. Attempt to connect to your VM. You'll get a popup with the INI file
   that's being pulled from proxmox.
      1. Locate the `proxy=` line and note the value. It is most likely the
      DNS name of your proxmox host.
   3. In your ini file, set the appropriate entries in the
   `[SpiceProxyRedirect]` section to translate the proxy value that Proxmox is
   including in the ini file to the IP address of the host you're attempting
   to connect to.
      1. For example, if the proxy being provided is `pve1.example.com:3128`
      and your proxmox host is 192.168.10.5 you would add the following line:
         1. `pve1.example.com:3128 = 192.168.10.5:3128`
      4. Once you've done this, set `inidebug=false` so it doesn't pop the
   ini debug back up.

**Comment by chaospup** [comment]
@joshpatten Thank You again for your assistance.  Thank you for all the hard work you have done on this solution and making it available to everyone, including the noobs.
