### ISSUE TITLE
[SpiceProxyRedirect] How to get infos

### ISSUE THREAD

**Issue by MightyMirko** [joshpatten/PVE-VDIClient#53]
Hello Josh,

thank you for this Software! 

However i dont understand what to put in here: 

  ```
# The Spice Proxy provided by the Proxmox API may need to have its host/port rewritten
# These rewrite rules are written `IP:port = IP:port`
# 1. Use the inidebug and read the current proxy=pve1.example.com:3128
# 2. Add your proxmox ip to the right side e.g. 123.123.123.123:6000
pve1.example.com:3128 = 123.123.123.123:6000
```
Left is FQDN from proxy and right side my ip of the proxmox host?
```

[virt-viewer]
type=spice
password=14a60aa38fab20d4e945590fa1c4b195a8fc6cd4
toggle-fullscreen=Shift+F11
tls-port=61000
proxy=http://my2ndFQDN:3128
delete-this-file=1
title=VM 100 - v100-u20-foxy
host=pvespiceproxy:64198b7e:100:myHostName::3dbce15a99118cc74b36b6ac1d813d8325fa3f4c
release-cursor=Ctrl+Alt+R
secure-attention=Ctrl+Alt+Ins
ca=-----BEGIN CERTIFICATE-----\n
....
-----END CERTIFICATE-----\n
host-subject=OU=PVE Cluster Node,O=Proxmox Virtual Environment,CN=my1stFQDN

```

**Comment by MightyMirko** [comment]
Ok got it :D

**Comment by MightyMirko** [comment]
Cant get Graphics Display - seems like something still missing :(

**Comment by MightyMirko** [comment]
I've added the ca certificate under 
[AdditionalParameters]
ca=--...
no luck..

**Comment by joshpatten** [comment]
Hosts are for connecting and authenticating against proxmox. You set the IP or FQDN of one or more of your proxmox hosts, followed by = and then the port number

What you need to implement is SpiceProxyRedirect to redirect http://my2ndFQDN:3128 to an actual host on your network

This is done by using the SpiceProxyRedirect section as follows:
`[SpiceProxyRedirect]
my2ndFQDN:3128=192.168.1.10:3128
`

where 192.168.1.10 is the IP address of the host in question.
