### ISSUE TITLE
Query only  re use on Arch Linux

### ISSUE THREAD

**Issue by thorrrr** [joshpatten/PVE-VDIClient#55]
Is there any way to use this in Arch i cannot find it in any repo

**Comment by joshpatten** [comment]
Try replacing the `apt install` line in the Linux installation instructions with the following line:
    sudo pacman -S tk python-pysimplegui python-pip

Then run the rest of the commands as they are in the instruction. If this works let me know and I'll update the instructions.

**Comment by RudiOnTheAir** [comment]
Thats interessting

I just installed on Endeavour Linux (Arch) the packages " python-pip, tk, git"

And it works... To be honest, it could be possible, that the package was already there...

**Comment by itsHanibee** [comment]
Yes it does work flawlessly on Arch: 

Distros that PVE-VDIClient have been tested on: `Mainline Arch and CachyOS.`

Install instructions;

- `sudo pacman -S tk yay python-pip git virt-viewer`

and then get `python-pysimplegui` from AUR using

- `yay -S python-pysimplegui`


you can then `git clone <REPO URL>` and cd there and run `python3 vdiclient.py` just like you would on Debian & Ubuntu and provided you have the config present it'll start right up.
