### ISSUE TITLE
[Feature Request] Auto Connect to VMID

### ISSUE THREAD

**Issue by Cerothen** [joshpatten/PVE-VDIClient#57]
It would be great to have the ability to automatically connect to a specific VMID if there is also a user and token specified. That coupled with autostart configurations on your favorite linux DE would make the whole connection process seamless right to the internal virtual machine.

```
[Authentication]
# This is the authentication backend that will be used to authenticate
auth_backend = pam
# If enabled, 2FA TOTP entry dialog will show
auth_totp = false
# If disabled, TLS certificate will not be checked
tls_verify = false
# User name (if using token)
user = user
# API Token Name
token_name = dvi
# API Token Value
token_value = xxx-x-x-x-xxx
# Auto Connect to specified VMID
auto_vmid = 100
```

**Comment by joshpatten** [comment]
This has been implemented with the latest release, see example ini file for implementation detail.

**Comment by Cerothen** [comment]
Awesome thanks, I will give it a try
