### ISSUE TITLE
Question: How to set VDIClient to kiosk = true but not the virt-viewer so usb option can be accessed.

### ISSUE THREAD

**Issue by pbvdven** [joshpatten/PVE-VDIClient#58]
Question: How to set VDIClient to kiosk = true but not the virt-viewer so usb option can be accessed but the vdiclient can not be closed.

the issue i have i can not get usb sticks to be auto discovered/added when using below options but it works when i pick the usb manual from the list.
# Enable USB passthrough
enable-usbredir = true
# Enable auto USB device sharing
enable-usb-autoshare = true

**Comment by joshpatten** [comment]
https://www.mankier.com/1/remote-viewer

You probably need to do something with 'usb-filter' in the AdditionalParameters section to define what devices you with to auto-share

In any case, I added a viewer_kiosk override option to give you this capability, See commit 9d75402
