### ISSUE TITLE
Feature request: could you add a forgot password button in the gui to open the default browser and go to a url that can be specified in the config.ini

### ISSUE THREAD

**Issue by pbvdven** [joshpatten/PVE-VDIClient#59]
I use ldap as authentication methode in proxmox it all works great. but i would love to have a forgot password button on the login screen so users can selfservice there password reset.

**Comment by joshpatten** [comment]
I will probably need to implement this to open a web browser or other program instead of just calling a URL, as this is done differently with every platform. Shouldn't be difficult to do.

**Comment by joshpatten** [comment]
Commit 2bac614 implements this feature. See the ini file example for implementation.
