### ISSUE TITLE
Unable to connect to graphic server

### ISSUE THREAD

**Issue by bclinton1** [joshpatten/PVE-VDIClient#60]
[vdiclient.txt](https://github.com/joshpatten/PVE-VDIClient/files/11746219/vdiclient.txt)

Hi friends. I almost have this awesome tool working. I am running into unable to connect graphic server as mentioned by another user below. I have tried the fix mentioned and cannot get past it. I have done the following along with my attached vdi.ini file that I modified. I figured I might check her with the experts before I blow something up. :)

**Changed the hosts entry in proxmox for the PVE n to

127.0.0.1 localhost.localdomain localhost
192.168.1.146 pve2.home.local pve2

# The following lines are desirable for IPv6 capable hosts

::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

**Comment by bclinton1** [comment]
Solution found. I added a redirect in my hosts file on the windows machine. Connects fine now.

192.168.1.146		pve2.home.local

**Comment by ChausseBenjamin** [comment]
> Solution found. I added a redirect in my hosts file on the windows machine. Connects fine now.
> 
> 192.168.1.146 pve2.home.local
> 
> Thanks again for this awesome tool!

You should probably close the issue to make it clearer to future people...
