### ISSUE TITLE
[Feature Request]  power control options for VMs

### ISSUE THREAD

**Issue by blindrain** [joshpatten/PVE-VDIClient#61]
Is there any way to add support for reboot/ hard reset options in the client?

Sometimes the VMs Hang and I have to log in to the web interface and use the reset option.  is there any way to add this to the client so my co-workers/ employees can do this without calling me?   
Also, there is apparently a hibernate and resume option now in the web interface it would be nice to have this as well in the client. 

Right now if Hibernate is used on the web interface.   vdi client connects to the machine but the system is in a frozen state until resume is selected in the web interface.

**Comment by joshpatten** [comment]
Let me see if I can add a right-click menu option to perform extra
functions like this.

**Comment by roberix** [comment]
Hi. 

We would be also very interested in this. 

Many thanks for your efforts @joshpatten 

Regards

rob

**Comment by joshpatten** [comment]
OK I created a new release which should cover this, give it a test and let me know if it works as you expect it. Note: you'll have to enable the reset option in the ini file, I've added the parameter to the example.
