### ISSUE TITLE
Unable to connect with proxmox 8

### ISSUE THREAD

**Issue by bclinton1** [joshpatten/PVE-VDIClient#64]
Hi friends....I had this working great with my proxmox 7.4 instance. I recently installed 8 on a spare workstation and am unable to connect. I get invalid username or password...try again. The user is added to proxmox and has the correct permissions. Not sure what I could be missing or if PVE-VDI has been tested with proxmox 8 yet.

**Comment by MacDonagal** [comment]
Hello, I've got the same error but it's was misconfiguration, I was trying to connect with PAM instead of pve authentification..

**Comment by bclinton1** [comment]
> Hello, I've got the same error but it's was misconfiguration, I was trying to connect with PAM instead of pve authentification..

That was it. Thank you my friend!

**Comment by MacDonagal** [comment]
You're welcome !
