### ISSUE TITLE
Can connect to a specific account on a multi-accounted Windows 10 VM?

### ISSUE THREAD

**Issue by takalasz** [joshpatten/PVE-VDIClient#68]
Hy!

I have a Win10 in Proxmox with multiple user accounts. Is there a method to login with a user to his/her corresponding account on that Win10 VM?

**Comment by joshpatten** [comment]
That's really more of a Microsoft RDS solution, this doesn't have any real 'hooks' into Windows to facilitate this, it is basically intended to be one virtual machine per user.
