### ISSUE TITLE
Resize window to see state and! connect button.

### ISSUE THREAD

**Issue by RudiOnTheAir** [joshpatten/PVE-VDIClient#69]
See Screenshot...

Running on Arch linux..

It would be nice if there where a config option to change the size... Manual resize is not possible, only scrolling the window inside...

 
![image](https://github.com/joshpatten/PVE-VDIClient/assets/47517341/de17cf3e-1cf4-41e0-a3e5-5b00256ceb79)

**Comment by joshpatten** [comment]
Resolved with [e848a93](https://github.com/joshpatten/PVE-VDIClient/commit/e848a938df4318f4b70e7399f8ae3763e4503b7b)
