### ISSUE TITLE
Window Resizing when Power Controls are enabled

### ISSUE THREAD

**Issue by BrickMyPhone** [joshpatten/PVE-VDIClient#71]
Hello,

with the new Power Controls everything works great only encountered one issue so far.

When having 5 VMs in the list the window is sized accordingly, but when having more than 5 VMs in the list the width is not resized accordingly, so I have to scroll left and right to get to the "Reset" and "Connect" buttons.

I have attached two screenshots, showcasing the issue, one with 5 VMs to my user and one with 6 VMs to my user.

Best Regards.
![5VMs](https://github.com/joshpatten/PVE-VDIClient/assets/145748739/c549e286-b026-46b4-b9fd-1ba9359bb3cf)
![6VMs](https://github.com/joshpatten/PVE-VDIClient/assets/145748739/447db2ac-4351-4a6b-b740-f9b196ad5538)

**Comment by BrickMyPhone** [comment]
With the window settings introduced in 1.2.02, according to the changelog:

#Set Window Dimensions. Only use if window isn't sizing properly
#window_width = 800
#window_height = 600

The window looks like this.

![image](https://github.com/joshpatten/PVE-VDIClient/assets/145748739/bcf7e50d-b4ad-4d4f-9b27-33b7f4923145)

**Comment by roberix** [comment]
Hi.

@joshpatten would it be possible to make a release including the change performed by @BrickMyPhone ?

Many thanks

Regards

Reinhard
