### ISSUE TITLE
-bash: /usr/local/bin/vdiclient.py: env: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by kabaga** [joshpatten/PVE-VDIClient#73]
Installed the VDIclient by following the instruction for Linux. I am on Raspberry Pi OS. As far as I know, it got installed without any issues.
When I ran the vdiclient.py, I got this error:
```
-bash: /usr/local/bin/vdiclient.py: env: bad interpreter: No such file or directory
```
This is the installation I followed:
```
apt install python3-pip python3-tk virt-viewer git
git clone https://github.com/joshpatten/PVE-VDIClient.git
cd ./PVE-VDIClient/
chmod +x requirements.sh
./requirements.sh
cp vdiclient.py /usr/local/bin
chmod +x /usr/local/bin/vdiclient.py
```
Then I created this file /etc/vdiclient/vdiclient.ini, and pretty much copied the example file.

**Comment by joshpatten** [comment]
What is the output when you run the command:

env python3

?

**Comment by kabaga** [comment]
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux.

I installed 3.10, but had to manually type-in 3.10, and this is the output:
env python3.10
Python 3.10.13 (main, Oct  3 2023, 17:10:40) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.

**Comment by joshpatten** [comment]
So if you change to your home folder (cd ~) and then run vdiclient.py, what
happens then?

Also, if that doesn't work, can you run:

env python3 /usr/local/bin/vdiclient.py

and make it work that way?

If you want to run python 3.10 you'll need to tell your OS to default to
the 3.10 installation. I'm not familiar with this process, but there are
guides out there.

**Comment by kabaga** [comment]
I installed 3.10 because it say on the guide.

It barked at me to install these two:
pip install proxmoxer
pip install PySimpleGUI

I ran requirements.sh, but the content is pip3. I reinstalled proxmoxer and PySimpleGUI via pip and I got the prompt now.

**Comment by Gidget19893161** [comment]
I too am having the same issue. I have followed MRP on YouTube to the letter. Will link below. At 13:15 he runs the command vdiclient.py this is what I get back 

eric@ThinClient-Laser:~ $ vdiclient.py
-bash: /usr/local/bin/vdiclient.py: env: bad interpreter: No such file or directory

so I run:

eric@ThinClient-Laser:~ $ python3 vdiclient.py
python3: can't open file '/home/eric/vdiclient.py': [Errno 2] No such file or directory

but if do:
eric@ThinClient-Laser:/usr/local/bin $ python3 vdiclient.py
I am able to get the splash screen with the same error he did.

not sure where I went wrong,
Linux is not really in my wheel house.

**Comment by joshpatten** [comment]
Well I went to load up RPi OS on my Pi and realized I have no idea where my HDMI adapter is.

I think I need to fully qualify the path for env in order for this to work, I'm about to commit that change, you can git pull to get the newest version in about 10 minutes.

**Comment by Gidget19893161** [comment]
I was just able to test it.  Started over from scratch. went as far as installing pi os lite for starch. It worked. I had an issue but got it resolved now i am having another issue. If i cant get it resolved i will start another ticket. thanks for doing that so fast!!!!

**Comment by joshpatten** [comment]
New release added, let me know if you run into any issues
