### ISSUE TITLE
Feature Request- Make the vdiclient to work with UNRAID VMs using spice

### ISSUE THREAD

**Issue by bparvez** [joshpatten/PVE-VDIClient#77]
First of all, thank you for your effort and this VDI Client has become necessary for my work from home requirements.

I also have some VMs running on UNRAID and I was wondering if it is possible to have a VDI Client to connect to VMs running on UNRAID using the spice protocol.

Thank you.

**Comment by joshpatten** [comment]
This client is only intended for Proxmox, and it would really be a whole separate project to do this for UNRAID.
