### ISSUE TITLE
Unable to connect to graphic server Error

### ISSUE THREAD

**Issue by mesab0ogie** [joshpatten/PVE-VDIClient#84]
I followed the instructions in this [video](https://www.youtube.com/watch?v=Vv3yUmbja1U&ab_channel=MRP)

The only difference is im using a Pi 3B+ booting directly from SD Card into Raspberry Pi OS Lite.

Managed to get everything set up and running, up till the login page. When i click on connect for my VM, i get a "unable to connect to graphic server" error. I've been searching and trying to find a solution for this for the last 2 days and im really pulling my hear right now trying to figure this out. 

I am able to connect to the VM via SPICE using virt-viewer on my macbook and everything seems to be working fine. I just cant get it to work on the Raspberry pi. Would really really appreciate it if someone could point me in the right direction. At this point i dont even know what is wrong as i followed the directions to the T. Even tried following the tutorial by apalrd(which seems outdated). Thank you in advance! 
![20231118_154727](https://github.com/joshpatten/PVE-VDIClient/assets/10762974/0a2b63d4-5169-4609-8a34-866aae400531)
![20231118_154742](https://github.com/joshpatten/PVE-VDIClient/assets/10762974/1796f224-c752-480e-8496-c59a55a1ca28)
![20231118_155550](https://github.com/joshpatten/PVE-VDIClient/assets/10762974/a9d641e8-ac7d-4828-91a8-9ad56853cdbb)

**Comment by billy995** [comment]
I have the same problem on Windows

**Comment by joshpatten** [comment]
This is because the SpiceProxyRedirect settings need set. Please read the comments in the config file example on how to set them to appropriately map your Proxmox hostnames to IP addresses or FQDNs.

**Comment by mesab0ogie** [comment]
Finally managed to solve the issue once the bug with the inidebug window was fixed. 

I was seeing the proxy pointing to mesa.server.local(mesa being my proxmox server name). Now i cannot remember setting any domains names for my proxmox server, but i did some google searching and came across a post to check the /etc/hosts file in  proxmox and saw that there was an entry for xyz.server.local and my server ip. Again i cannot for the life of me remember setting that, but i did assign  a local domain name to my proxmox instance in my dns server(proxmox.mesalocal) which is different from the one is the hosts file. So i changed the domain name, and saved the file. Then i added the correct domain in the SpiceProxy section in the config file(http://proxmox.mesalocal:8123). Fired up vdiclient.py again and voila, it works.

So if anyone is having the same issue, look in your /etc/hosts file and make sure you have the right domain name and use the exact name in the SpiceProxy config. Hope this helps.
