### ISSUE TITLE
Issue with Spice

### ISSUE THREAD

**Issue by walstib2** [joshpatten/PVE-VDIClient#9]
First - Thanks for a great program!  Now on to the issue :)

I have  Proxmox running remotely in a Lab at school and as a server here at the house. When connecting through the web interface and launching a Spice session  Remote-Viewer connects and launches a window automatically with no issues.  I am able to connect to either server with the test account and see a list of VMs the user is authorized to use.  The issue that happens is that Virt Viewer pops up a window saying it is "unable to connect to the graphic server" 

Some things I have tried -  Turning off all Windows Firewall and Anti Virus Settings - Same Error
                                        - Setting the spice port in the vdiclient.ini file                     - same error

I am running Windows 11, so I'm not sure if that is part of the issue.  I plan on testing on Windows 10 when I return to work Monday.
Just wondering if you had any other ideas since both servers work with the web browser downloading the .vv file, but both fail with the same error in the app. 

Look forward to seeing where this program goes.

Greg

**Comment by walstib2** [comment]
Ok found something that may be causing the issue:

the file downloaded from  the website has  this line:   proxy=http://prox.ctisandbox.cfcc.edu:3128

In the INI debug  it has this line:  proxy = http://pve2.ctisandbox.cfcc.edu:3128

It is using the node (host) name instead of the domain name.  Otherwise, the two files appear to be identical.  

I tried overriding it by using prox2.ctisandbox.cfcc.edu:3128 =70.63.86.168:3128 in the ini file.

But it still shows the  proxy = http://pve2.ctisandbox.cfcc.edu:3128  instead of the IP address

I know this would not work long-term.  but was hoping it would give us proof that this was the issue...

Greg

**Comment by jpattWPC** [comment]
would it not need to be `pve2.ctisandbox.cfcc.edu:3128=70.63.86.168:3128` in the ini file instead?

Here is the logic that looks for the exact value you're receiving in the spice configuration:

![image](https://user-images.githubusercontent.com/16338864/162823741-931c0daf-f61d-4ac2-90e1-1cbc299067c5.png)

It strips off `http://` (first 7 characters) off the front of the proxy value and if the string matches an entry in your config file it will replace it.

**Comment by walstib2** [comment]
You are 100% correct.   Sometimes I can't see the forest for the trees :)    Works great now!

Thank you again for a great program.  This will make it much easier to have the students working remotely on labs.

Greg

**Comment by walstib2** [comment]
Quick easy fix that was my mistake
