### ISSUE TITLE
VDIClient From Windows 11

### ISSUE THREAD

**Issue by addelovein** [joshpatten/PVE-VDIClient#90]
Having some issues Running or Building the client...

running ./vdiclient.py it flashes a command prompt and then dissapears....

Trying to build first it couldnt find pyinstaller

i edited the BAT file and changed that to python -m PyInstaller and it continued...

But then I come to the following....

Could Not Find C:\Users\AddeLovein\source\repos\PVE-VDIClient\dist\vdiclient\opengl32sw.dll
Could Not Find C:\Users\AddeLovein\source\repos\PVE-VDIClient\dist\vdiclient\libGLESv2.dll
Could Not Find C:\Users\AddeLovein\source\repos\PVE-VDIClient\dist\vdiclient\d3dcompiler_47.dll
Could Not Find C:\Users\AddeLovein\source\repos\PVE-VDIClient\dist\vdiclient\Qt5Pdf.dll
Could Not Find C:\Users\AddeLovein\source\repos\PVE-VDIClient\dist\vdiclient\Qt5VirtualKeyboard.dll
Could Not Find C:\Users\AddeLovein\source\repos\PVE-VDIClient\dist\vdiclient\Qt5WebSockets.dll
Could Not Find C:\Users\AddeLovein\source\repos\PVE-VDIClient\dist\vdiclient\Qt5Quick.dll
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.

**Comment by addelovein** [comment]
It does create an MSI Package however resulting with the following:
Traceback (most recent call last):
  File "vdiclient.py", line 911, in <module>
  File "vdiclient.py", line 886, in main
  File "vdiclient.py", line 734, in loginwindow
  File "vdiclient.py", line 249, in setmainlayout
KeyError: 'DEFAULT'

**Comment by joshpatten** [comment]
I've committed a fix for the build batch file, though the errors you were
seeing were innocuous.

Regarding the second issue, can you reply with a copy of your INI file?

**Comment by addelovein** [comment]
[General]
title = VDI Login
theme = LightBlue
icon = vdiicon.ico
logo = vdiclient.png
kiosk = False
fullscreen = True
inidebug = True
# Select which guest types to display. Acceptable values: both, lxc, qemu
guest_type = both
# Show VM option for resetting VM
#show_reset = True
# Set Window Dimensions. Only use if window isn't sizing properly
#window_width = 800
#window_height = 600

# PVE-VDIClient supports multiple clusters. Define them with sections that start with Hosts. followed by the name
# you wish to display to your end users. This example is Hosts.PVE which would display PVE to your users
[Hosts]
# JSON dictionary of servers in the cluster
# Format is 'IP/FQDN': PORT
# NOTE: MAKE SURE THAT ALL LINES ARE INDENTED
hostpool = {
               "192.168.0.10" : 8006,
               "192.168.0.8" : 8006,
               "192.168.0.7" : 8006
           }
# This is the authentication backend that will be used to authenticate
auth_backend = pve
auth_totp = false
tls_verify = false
# User name (if using token)
# NOTE: If only one cluster is defined, this will auto-login
# If user, token_name, and token_value are set
#user = user
# API Token Name
#token_name = dvi
# API Token Value
#token_value = xxx-x-x-x-xxx
# Password Reset Command Launch. Has to be full executable Command
#pwresetcmd = start chrome --app=http://pwreset.example.com
# Automatically connect to a VMID upon authentication
#auto_vmid = 100

# An additional cluster definition
#[Hosts.PVE2]
# JSON dictionary of servers in the cluster
# Format is 'IP/FQDN': PORT
#hostpool = {
#               "10.10.10.100" : 8006,
#               "10.10.10.111" : 8006,
#               "pve1.example.com" : 8006
#           }
# This is the authentication backend that will be used to authenticate
#auth_backend = pve
# If enabled, 2FA TOTP entry dialog will show
#auth_totp = false
# If disabled, TLS certificate will not be checked
#tls_verify = false
# User name (if using token)
# NOTE: If only one cluster is defined, this will auto-login
#user = user
# API Token Name
#token_name = dvi
# API Token Value
#token_value = xxx-x-x-x-xxx
# Password Reset Command Launch. Has to be full executable Command
#pwresetcmd = start chrome --app=http://pwreset.example.com
# Automatically connect to a VMID upon authentication
#auto_vmid = 100


[SpiceProxyRedirect]
# The Spice Proxy provided by the Proxmox API may need to have its host/port rewritten
# These rewrite rules are written `IP:port = IP:port`
# 1. Use the inidebug and read the current proxy=pve1.example.com:3128
# 2. Add your proxmox ip to the right side e.g. 123.123.123.123:6000
# pve1.example.com:3128 = 123.123.123.123:6000

#[AdditionalParameters]
# If you wish to define additional parameters to pass to virt-viewer you may define them here
# More parameter definitions here: https://www.mankier.com/1/remote-viewer
# Some Examples:
# Enable USB passthrough
#enable-usbredir = true
# Enable auto USB device sharing
#enable-usb-autoshare = true

**Comment by joshpatten** [comment]
Try renaming [Hosts] to [Hosts.PVE]

**Comment by addelovein** [comment]
That did the trick.... 

If i add 
[Authentication]  it says Hosts is missing though..

Is[Authentication] deprecated?

**Comment by joshpatten** [comment]
All of the authentication options were moved into each 'Hosts.YYY' section,
so that you can define multiple Proxmox clusters, so the 'Authentication'
section is deprecated.

**Comment by addelovein** [comment]
host = pvespiceproxy:65a56738:601:pve4::79e6861a96f0519f56867d11665d9ce13b8a36b0

Last questions ;-)
The Above is shown in debug got a feeling i need to add something to the [SpiceProxyRedirect]

**Comment by addelovein** [comment]
Ok thanks all solved... Just trying to figure out how to supply the ini with the msi....
