### ISSUE TITLE
Windows Size and VM-List

### ISSUE THREAD

**Issue by addelovein** [joshpatten/PVE-VDIClient#91]
VM List should really be snapped to the window size...

Picture explains it all...
![Screenshot 2024-01-16 111716](https://github.com/joshpatten/PVE-VDIClient/assets/24968297/0fa1f638-4908-47dd-aabb-7636863359e8)

**Comment by addelovein** [comment]
Added property Show Only Vertical scrollbars... Did the trick

**Comment by blindrain** [comment]
where did you put that property?
