### ISSUE TITLE
Please add in requirements package version

### ISSUE THREAD

**Issue by billy995** [joshpatten/PVE-VDIClient#99]
Please add in requirements the package version because PySimpleGUI need in V5.0.0 license Key but not in V4.60.5

**Comment by joshpatten** [comment]
I am not seeing anything about a license key anywhere, can you reply with
some information about this?

**Comment by joshpatten** [comment]
Well I see it now, how absolutely absurd. This kinda ruins the project and
makes things untenable long term. Not sure what I'm going to do about
this...

**Comment by joshpatten** [comment]
Set the maximum version of pysimplegui to <5.0.0, will have to find an alternative in the future...
